Building with Responsive Design
tacodtripe/The-Next-Web-Clone pull request #1
Opened 2020-03-12 20:34 UTC by tacodtripe

2020-03-18 22:49 UTC, majovanilla requested changes
Hey team!

## You did a *great* job on this project! 💜 
- Good Readme file
- Good Pull Request Message


There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- [x] Your project's width it's not the right one. Below 1200px the original page has very small margins, and at some smaller screen sizes, some elements occupy 100% width. Please check this and adjust your page.

- [ ] As you will see in the comments below, the breakpoints you are using are not 100% the same as the original page and when you are close to the break, the page doesn't have the same look as the original page. Please check this out.

- [ ] Take another look at the fonts because in different sections they lose proportion. Make sure they have the same size as the original page and take a closer look at how they change when you change screen sizes.

- [ ] Check the rest of the comments below.


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-18 22:49 UTC, majovanilla commented on index.html
> +        </a>
- [ ] Check the size of the logo in the tablet and mobile versions. It's not behaving correctly.
![Screenshot from 2020-03-18 16-19-01](https://user-images.githubusercontent.com/51926937/77012993-b985f000-6934-11ea-9604-74afa007c874.png)
![Screenshot from 2020-03-18 16-19-16](https://user-images.githubusercontent.com/51926937/77012996-bab71d00-6934-11ea-862e-78fedd8b01fb.png)

2020-03-18 22:49 UTC, majovanilla commented on index.html
> +                    </div>
- [ ] Check the size of the articles' images in the mobile version. They should be smaller.

- [ ] Check the section's title. It should be bold and larger.

![Screenshot from 2020-03-18 16-24-52](https://user-images.githubusercontent.com/51926937/77013151-1386b580-6935-11ea-8b72-527b9279ef48.png)

Original:
![Screenshot from 2020-03-18 16-24-59](https://user-images.githubusercontent.com/51926937/77013157-17b2d300-6935-11ea-81bc-068a05211a1d.png)

- [ ] Check the tablet version. The articles should display three in a row. This happens around 990px screen size, so take a look at your media queries px. Yours are like:
![Screenshot from 2020-03-18 16-26-06](https://user-images.githubusercontent.com/51926937/77013254-4cbf2580-6935-11ea-8d43-abe7b76eab0e.png)

Should be like:
![Screenshot from 2020-03-18 16-26-14](https://user-images.githubusercontent.com/51926937/77013272-5183d980-6935-11ea-97a2-595fb6c52e59.png)

2020-03-18 22:49 UTC, majovanilla commented on index.html
> +                        <a class="funding-navbar-a last-nav-item" href="#">See more</a>
- [ ] This section also displays differently around 990px. It should have 3 elements and occupy 100% width but it's showing this:
![Screenshot from 2020-03-18 16-30-00](https://user-images.githubusercontent.com/51926937/77013461-bb03e800-6935-11ea-8bee-07a8a091c08f.png)

The original:
![Screenshot from 2020-03-18 16-30-00](https://user-images.githubusercontent.com/51926937/77013485-c525e680-6935-11ea-8ced-14e370de9f0b.png)
![Screenshot from 2020-03-18 16-30-19](https://user-images.githubusercontent.com/51926937/77013488-c5be7d00-6935-11ea-8cd5-bf7cebb38739.png)

- [ ] There's a moment when this section has two articles in one row, that never happens on the original page. Please fix it.
![Screenshot from 2020-03-18 16-31-00](https://user-images.githubusercontent.com/51926937/77013593-f43c5800-6935-11ea-8d80-ca91578a9025.png)

- [ ] In the mobile and desktop version the image it's too big. Please adjust it.
![Screenshot from 2020-03-18 16-32-02](https://user-images.githubusercontent.com/51926937/77013643-0fa76300-6936-11ea-9572-4929b6560195.png)

![Screenshot from 2020-03-18 16-33-09](https://user-images.githubusercontent.com/51926937/77013698-2fd72200-6936-11ea-8a87-fc6001750ebf.png)

2020-03-18 22:49 UTC, majovanilla commented on index.html
> +                            <h5 class="rubric-second-title"><a class="rubric-second-title" href="#">Napier Lopes</a> - 20 hours ago</h5>
- [ ] All the articles in this section should rearrange in the tablet version to two in a row. Your page shows three at some point. This is also related to the media query, so check your px breaks.

- [ ] When changing to the mobile version, your articles are displaying in two columns when they should occupy 100% width. Check the breakpoints to match the original page!

- [ ] In the mobile version your titles are not sized appropriately (The main title is too small and the red titles too large).  Check the font size and make sure they are also responsive.

2020-03-18 22:49 UTC, majovanilla commented on index.html
> +
- [ ] This section has larger images in the mobile version too. Once you fix the Latest news, you will fix this one if they have the same classes.

2020-03-18 22:49 UTC, majovanilla commented on style.css
> +    display: grid;
- [ ] This media query is giving some issues, please check that is the correct `max-width`

2020-03-18 22:49 UTC, majovanilla commented on style.css
> +  }
- [ ] Check this one, too!

2020-03-20 00:46 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-03-20 00:47 UTC, addod19 requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, you have really done a great job working on the comments by the previous TSE 😄 We are almost there, let us improve the code by making the project responsive by removing the horizontal scroll on ```small screen```
![ffx](https://user-images.githubusercontent.com/46388113/77127436-57b4ab80-6a44-11ea-99d2-0208475aeff1.PNG)

- Kindly add a hover effect to the links as in the original

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
You can find me on slack Daniel Larbi Addo

2020-03-20 17:34 UTC, addod19 approved these changes
## Status: Approved 🏆 🎈 

Hi @tacodtripe  and @CalyCherkaoui, congratulations 👍 on fixing all the comments by the previous TSE's. Our project looks great and it is very responsive 😄 I hereby approve the project. Kindly go ahead and merge to master and submit project completion form ✋ 
[OPTIONAL]
Kindly fix the image display in the readme file. The Image is not displaying

Good luck with your next projects 
_Happy coding_ 👨‍💻 👩‍💻 
Daniel Larbi Addo

2020-03-20 17:59 UTC, merged